require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2.3
  Exclude:
    - db/schema.rb
    - db/migrate/*.acts_as_taggable_on_engine.rb

Metrics:
  Exclude:
    - db/migrate/*.rb
    - db/seeds.rb

Metrics/LineLength:
  Max: 120

Rails/Output:
  Exclude:
    - db/seeds.rb

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update
